### ISSUE TITLE
libomp.so: cannot open shared object file

### ISSUE THREAD

**Issue by kondors1995** [Neutron-Toolchains/neutron-clang#1]
Error

<img width="844" alt="image" src="https://user-images.githubusercontent.com/7190697/199211322-daf2d81b-5e3c-4d32-a9dc-3875c826978a.png">

OS latest ubuntu

**Comment by beakthoven** [comment]
> Error
> 
> <img alt="image" width="844" src="https://user-images.githubusercontent.com/7190697/199211322-daf2d81b-5e3c-4d32-a9dc-3875c826978a.png">
> 
> OS latest ubuntu

Neutron Clang is linked against openmp libraries; to resolve the problem, install the LLVM openmp runtime libraries. It's the 'libomp-dev' package on Debian-based distros.

**Comment by kondors1995** [comment]
I have this installed on ubuntu

**Comment by beakthoven** [comment]
> I have this installed on ubuntu

That's strange. Could you please run `ldd path/to/clang` or  `ldd path/to/ld.lld` and send the output?

**Comment by kondors1995** [comment]
its might be due to running it in WSL

**Comment by kondors1995** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/7190697/199252396-ab9d8a1c-7785-439b-974c-49b894d21edf.png">

**Comment by beakthoven** [comment]
> <img alt="image" width="680" src="https://user-images.githubusercontent.com/7190697/199252396-ab9d8a1c-7785-439b-974c-49b894d21edf.png">

You misunderstood me; when I said "path/to/clang," I meant the absolute path to neutron's clang binary.

**Comment by kondors1995** [comment]
like this?
<img width="891" alt="image" src="https://user-images.githubusercontent.com/7190697/199255195-8f064405-ebe2-4447-86dd-b7e2f5c13fa8.png">

**Comment by beakthoven** [comment]
> like this? <img alt="image" width="891" src="https://user-images.githubusercontent.com/7190697/199255195-8f064405-ebe2-4447-86dd-b7e2f5c13fa8.png">

You are using `lld` which is a linker. Please run it using `ldd`

**Comment by kondors1995** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/7190697/199257649-812451f5-4efc-4f1f-96b1-b4b4979cf9b2.png">

**Comment by kondors1995** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/7190697/199257810-d2da5956-f695-4be1-bf80-9fa6dba61493.png">

**Comment by dakkshesh07** [comment]
> <img alt="image" width="884" src="https://user-images.githubusercontent.com/7190697/199257810-d2da5956-f695-4be1-bf80-9fa6dba61493.png">

Yeah, as you can see libomp.so is not available, Please double check if you have LLVM openmp runtime library installed.

**Comment by beakthoven** [comment]
> <img alt="image" width="884" src="https://user-images.githubusercontent.com/7190697/199257810-d2da5956-f695-4be1-bf80-9fa6dba61493.png">

Could you try adding '/usr/lib' to the binaries' rpath?
Try executing [this](https://bin.cyberknight777.dev/u2EX) in neutron clang's directory. Note that you need `patchelf` package.

**Comment by beakthoven** [comment]
@kondors1995 I personally use ArchLinux on my PCs, and libraries are correctly identified.
> ![image](https://user-images.githubusercontent.com/64984008/199469638-554f40b9-efe5-4c7f-ae14-04a3f26c7ee5.png)

I'll test on Ubuntu through VM or WSL in a bit. Could you specify your Ubuntu version?

**Comment by kondors1995** [comment]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/7190697/199481951-c876fe24-d248-422a-848e-bc5b21711a25.png">

**Comment by beakthoven** [comment]
> <img alt="image" width="494" src="https://user-images.githubusercontent.com/7190697/199481951-c876fe24-d248-422a-848e-bc5b21711a25.png">

I tried a few things on my Ubuntu installation, but nothing appears to work. In the next neutron clang build, I will statically link openmp libs to eliminate runtime openmp lib dependency and thus address this issue.

**Comment by kondors1995** [comment]
Thank you.

**Comment by beakthoven** [comment]
@kondors1995 Okay, I believe I've identified the problem. It turns out that only `libomp5.so` and `libomp.so.5` are available in `/lib/x86_64-linux-gnu/`. However, our clang binaries look for `libomp.so` in `/lib/x86_64-linux-gnu/`.

Because libomp.so is installed at `/lib/llvm-15/lib/libomp.so` on Ubuntu, making a symlink with `sudo ln -s /lib/llvm-15/lib/libomp.so /lib/x86_64-linux-gnu/libomp.so` resolves the issue.

> ![image](https://user-images.githubusercontent.com/64984008/199511741-48e5a036-ec03-40c9-9799-c29d18fa4979.png)

Having said that, I will also use statically linked openmp libs with clang in my next build to avoid problems like these.

**Comment by beakthoven** [comment]
Please let me know whether the symlink resolved problem for you as well.

**Comment by kondors1995** [comment]
<img width="821" alt="image" src="https://user-images.githubusercontent.com/7190697/199519237-e6385b64-769b-4688-bb21-7df74b9808e3.png">

**Comment by beakthoven** [comment]
> <img alt="image" width="821" src="https://user-images.githubusercontent.com/7190697/199519237-e6385b64-769b-4688-bb21-7df74b9808e3.png">

Perfect! So i will close this issue then.
